# Generated by Django 4.2.20 on 2025-08-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-question', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría de Soporte',
                'verbose_name_plural': 'Categorías de Soporte',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Ticket')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Descripción del Problema')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('ai_response', models.TextField(blank=True, verbose_name='Respuesta de AI')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Confianza de AI (0-1)')),
                ('is_resolved_by_ai', models.BooleanField(default=False, verbose_name='Resuelto por AI')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calificación (1-5)')),
                ('feedback', models.TextField(blank=True, verbose_name='Comentarios del Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_response', models.BooleanField(default=False, verbose_name='Respuesta de IA')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('ai_context', models.JSONField(blank=True, default=dict, verbose_name='Contexto de AI')),
                ('ai_tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens Utilizados')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Mensaje de Soporte',
                'verbose_name_plural': 'Mensajes de Soporte',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('keywords', models.TextField(help_text='Separadas por comas', verbose_name='Palabras Clave')),
                ('embedding_vector', models.JSONField(blank=True, default=list, verbose_name='Vector de Embedding')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Utilizado')),
                ('effectiveness_score', models.FloatField(default=0.0, verbose_name='Puntuación de Efectividad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportcategory')),
            ],
            options={
                'verbose_name': 'Artículo de Base de Conocimiento',
                'verbose_name_plural': 'Base de Conocimiento',
                'ordering': ['-effectiveness_score', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('keywords', models.TextField(help_text='Separadas por comas', verbose_name='Palabras Clave')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Veces Vista')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='Votos Útiles')),
                ('not_helpful_votes', models.PositiveIntegerField(default=0, verbose_name='Votos No Útiles')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportcategory')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['-is_featured', '-helpful_votes', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('conversation_data', models.JSONField(default=dict, verbose_name='Datos de la Conversación')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('user_satisfaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satisfacción (1-5)')),
                ('was_helpful', models.BooleanField(blank=True, null=True, verbose_name='Fue Útil')),
                ('escalated_to_human', models.BooleanField(default=False, verbose_name='Escalado a Humano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Conversación AI',
                'verbose_name_plural': 'Historial de Conversaciones AI',
                'ordering': ['-updated_at'],
            },
        ),
    ]
