# Generated by Django 4.2.20 on 2025-08-02 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Solo visible para staff'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'Usuario'), ('ai', 'AI Assistant'), ('human', 'Soporte Humano'), ('system', 'Sistema'), ('status_change', 'Cambio de Estado'), ('assignment_change', 'Cambio de Asignación'), ('notification', 'Notificación'), ('closure', 'Cierre de Ticket')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='new_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_message_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='previous_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_message_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SupportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Ticket Creado'), ('ticket_updated', 'Ticket Actualizado'), ('ticket_resolved', 'Ticket Resuelto'), ('ticket_closed', 'Ticket Cerrado'), ('new_message', 'Nuevo Mensaje'), ('status_changed', 'Estado Cambiado'), ('assigned', 'Ticket Asignado'), ('unassigned', 'Ticket Desasignado')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Soporte',
                'verbose_name_plural': 'Notificaciones de Soporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
