# Generated by Django 4.2.20 on 2025-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio con descuento manual', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='¿Está en oferta?'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_alert',
            field=models.PositiveIntegerField(default=5, help_text='Alerta cuando el stock sea menor a este valor'),
        ),
    ]
