# Generated by Django 4.2.20 on 2025-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('webpay', 'Webpay Plus'), ('transfer', 'Transferencia Bancaria'), ('cash', 'Pago contra entrega')], default='webpay', max_length=20),
        ),
    ]
