# Generated by Django 4.2.20 on 2025-07-31 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('account_type', models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Cuenta de Ahorros'), ('vista', 'Cuenta Vista')], default='checking', max_length=20, verbose_name='Tipo de Cuenta')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Titular de la Cuenta')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT del Titular')),
                ('email_notification', models.EmailField(max_length=254, verbose_name='Email para Notificaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['bank_name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='TransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Transferido')),
                ('transfer_date', models.DateTimeField(verbose_name='Fecha de Transferencia')),
                ('reference_number', models.CharField(max_length=50, verbose_name='Número de Referencia/Comprobante')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Nombre del Emisor')),
                ('sender_rut', models.CharField(max_length=12, verbose_name='RUT del Emisor')),
                ('sender_bank', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('receipt_image', models.ImageField(help_text='Sube una imagen del comprobante de transferencia', upload_to='transfer_receipts/%Y/%m/%d/', verbose_name='Comprobante de Transferencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Verificación'), ('verified', 'Verificado y Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, verbose_name='Notas de Verificación')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.bankaccount', verbose_name='Cuenta de Destino')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_payment', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Pago por Transferencia',
                'verbose_name_plural': 'Pagos por Transferencia',
                'ordering': ['-created_at'],
            },
        ),
    ]
