# Generated by Django 4.2.20 on 2025-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bankaccount_transferpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Verificación'), ('verified', 'Verificado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20),
        ),
    ]
