# Generated by Django 4.2.20 on 2025-08-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_transferpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Verificación'), ('verified', 'Verificado - Esperando Aprobación'), ('approved', 'Aprobado y Pagado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20),
        ),
    ]
