# Generated by Django 4.2.20 on 2025-08-02 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_transferpayment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historial de Estados'},
        ),
        migrations.RenameField(
            model_name='orderstatushistory',
            old_name='status',
            new_name='new_status',
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('processing', 'En Preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('webpay', 'Webpay Plus (No disponible)'), ('transfer', 'Transferencia Bancaria'), ('cash', 'Pago contra entrega')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el cambio'),
        ),
        migrations.CreateModel(
            name='OrderPaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_payment_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], max_length=20, null=True)),
                ('new_payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio de pago')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pago',
                'verbose_name_plural': 'Historial de Estados de Pago',
                'ordering': ['-changed_at'],
            },
        ),
    ]
